name: Set environment variables

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  job:
    env:
      SCHEMAS_URL: https://raw.githubusercontent.com/lambda-feedback/request-response-schemas/master/
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2